instance:
  _target_: models.comparative_regression_adm.OutlinesTransformersComparativeRegressionADM
  precision: half
  mode: demo
  sampler:
    _target_: outlines.samplers.GreedySampler
  model_name: mistralai/Mistral-7B-Instruct-v0.3
inference_kwargs:
  kdma_score_examples: true
  num_samples: 1
  predict_outcomes: false
  generator_batch_size: 5
  incontext:
    sort_actions: true
    normalization: null
    number: 5
    leave_one_out_strategy: null
    most_similar_first: false

force_determinism: true
align_to_target: true
save_last_unstructured_state_per_scenario: true
