instance:
  _target_: align_system.algorithms.outlines_adm.OutlinesTransformersADM

  model_name: mistralai/Mistral-7B-Instruct-v0.2
  baseline: false
  mode: demo
  sampler:
    _target_: outlines.samplers.GreedySampler

